package paneldomotico.ui;

import javax.swing.event.ChangeListener;
import paneldomotico.dominio.Habitacion;

/**
 * Implementacion de la vista del panel de calefaccion
 * 
 * @author aleniet
 * @author davmele
 */
public class CalefaccionUI extends javax.swing.JFrame {
    private ControladorCalefaccion controlador;
    private Habitacion habitacion;
    
    /**
     * Inicializador
     * 
     * @param habitacion el modelo de la habitacion
     * @throws NullPointerException si el modelo dado es igual a null
     */
    public CalefaccionUI(Habitacion habitacion) {
        if(habitacion == null){
            throw new NullPointerException("Modelo de habitacion igual a null");
        }
        initComponents();
        this.habitacion = habitacion;
        controlador = new ControladorCalefaccion(this, habitacion);
        setNivelTemperatura(habitacion.getTemperatura());
    }
    
    /**
     * Modifica el nivel de temperatura
     * 
     * @param temperatura la nueva temperatura
     */
    public void setNivelTemperatura(double temperatura){
        ChangeListener cl = ajustarTemperatura.getChangeListeners()[0];
        ajustarTemperatura.removeChangeListener(cl);
        textoTemperatura.setText(temperatura+"℃");
        ajustarTemperatura.setValue((int) temperatura);
        ajustarTemperatura.addChangeListener(cl);     
    }
    
    /**
     * Devuelve la temperatura ajustada
     * 
     * @return un int con la temperatura
     */
    public int getTemperatura(){
        return ajustarTemperatura.getValue();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ajustarTemperatura = new javax.swing.JSlider();
        jPanel1 = new javax.swing.JPanel();
        textoTemperatura = new javax.swing.JLabel();
        aumentarTemperatura = new javax.swing.JButton();
        disminuirTemperatura = new javax.swing.JButton();
        volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Panel de control de calefacción");
        setLocation(new java.awt.Point(500, 400));

        ajustarTemperatura.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ajustarTemperatura.setMajorTickSpacing(1);
        ajustarTemperatura.setMaximum(30);
        ajustarTemperatura.setMinimum(12);
        ajustarTemperatura.setMinorTickSpacing(2);
        ajustarTemperatura.setPaintLabels(true);
        ajustarTemperatura.setPaintTicks(true);
        ajustarTemperatura.setValue(20);
        ajustarTemperatura.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ajustarTemperaturaStateChanged(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        textoTemperatura.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        textoTemperatura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoTemperatura.setText("20.0℃");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        aumentarTemperatura.setBackground(new java.awt.Color(255, 102, 102));
        aumentarTemperatura.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        aumentarTemperatura.setText("+");
        aumentarTemperatura.setFocusPainted(false);
        aumentarTemperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aumentarTemperaturaActionPerformed(evt);
            }
        });

        disminuirTemperatura.setBackground(new java.awt.Color(153, 204, 255));
        disminuirTemperatura.setFont(new java.awt.Font("Dialog", 0, 100)); // NOI18N
        disminuirTemperatura.setText("-");
        disminuirTemperatura.setFocusPainted(false);
        disminuirTemperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disminuirTemperaturaActionPerformed(evt);
            }
        });

        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ajustarTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(volver)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(disminuirTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(aumentarTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(disminuirTemperatura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(aumentarTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(ajustarTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(volver, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aumentarTemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aumentarTemperaturaActionPerformed
        controlador.aumentarTemperatura();
    }//GEN-LAST:event_aumentarTemperaturaActionPerformed

    private void disminuirTemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disminuirTemperaturaActionPerformed
        controlador.disminuirTemperatura();
    }//GEN-LAST:event_disminuirTemperaturaActionPerformed

    private void ajustarTemperaturaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ajustarTemperaturaStateChanged
        controlador.temperaturaAjustada();
    }//GEN-LAST:event_ajustarTemperaturaStateChanged

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        controlador.volver();
    }//GEN-LAST:event_volverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider ajustarTemperatura;
    private javax.swing.JButton aumentarTemperatura;
    private javax.swing.JButton disminuirTemperatura;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel textoTemperatura;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
